### ISSUE TITLE
IE theme

### ISSUE THREAD

**Issue by provalinf** [bokiscout/VivaldiThemeCreator#1]
Hello,
It is possible to have transparency aero as in ie?
And also to use bookmarks in just clicking once?
Thank you

**Comment by bokiscout** [comment]
About transparency:
- As much as I know about how Vivaldi's UI is done it is not possible with ease. Maybe with little more thinkering about it it will be possible but I haven't tried.
- Will take a look later this month.

About bookmark stuff:
- Please be more precise about what do you mean by "just clicking once".

**Comment by bokiscout** [comment]
About bookmarks:
Bookmarks can be opened by one click in version 1.2.490.43, I don't know if this was possible in previous versions.

 Go to Settings -> Bookmarks -> and check 'Open Bookmark Panel Items with Single click'

About Aero transparency:
Aero Transparency as in IE is not possible.
